modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="crafttweak"
version="1.0.0"
displayName="craftTweak"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="woodteacup"

[[dependencies.crafttweak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




